runtime: nodejs18
env: standard
env_variables:
    NODE_ENV: "PROD"
    POSTGRES_HOST: "/cloudsql/infinite-deck-397306:europe-west6:hello-world-dev"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "aabbccdd"
    POSTGRES_DATABASE: "postgres"
    POSTGRES_SCHEMA: "node-hw"
    POSTGRES_MESSAGES_TABLE: "messages"
    POSTGRES_USERS_TABLE: "users"
    POSTRGES_TOKENS_TABLE: "tokens"
    JWT_SECRET: "secret"
    SERVER_URL: "https://infinite-deck-397306.oa.r.appspot.com"
handlers:
    - url: /.*
      script: auto
