steps:
    - name: "gcr.io/cloud-builders/docker"
      id: "build image"
      args:
          ["build", "-t", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA", "."]

    - name: "gcr.io/cloud-builders/docker"
      id: "push to GCR"
      args: ["push", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"]

    - name: "gcr.io/cloud-builders/gcloud"
      id: "deploy to Cloud Run"
      entrypoint: "bash"
      args:
          - "-c"
          - |
              secrets_list=$(gcloud secrets list --filter="labels.appengine=env" --format="value(name)")

              env_vars=""

              for secret_name in $secrets_list; do
                secret_value=$(gcloud secrets versions access latest --secret=$secret_name)
                env_vars="${env_vars}${secret_name}=${secret_value},"
              done

              env_vars=$(echo $env_vars | sed 's/,$//')

              gcloud run deploy safwan-node-express-hw \
                --image gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA \
                --region europe-west3 \
                --platform managed \
                --allow-unauthenticated \
                --set-env-vars $env_vars

    - name: "gcr.io/cloud-builders/git"
      id: "check-logToBigQuery-changes"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              if git diff --name-only $COMMIT_SHA | grep "cloud-functions/log-to-big-query"; then
                echo "Changes detected in logToBigQuery!"
                touch /workspace/logToBigQuery-changes
              else
                echo "No changes in logToBigQuery."
              fi

    - name: "gcr.io/cloud-builders/gcloud"
      id: "deploy logToBigQuery cloud function"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              if [ -f /workspace/logToBigQuery-changes ]; then
                gcloud functions deploy logToBigQuery --runtime nodejs18 --trigger-topic logs-topic --region europe-west3 --memory 128MB --source cloud-functions/log-to-big-query
              fi

    - name: "gcr.io/cloud-builders/git"
      id: "check-processErrorLogs-changes"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              if git diff --name-only $COMMIT_SHA | grep "cloud-functions/store-error-requests"; then
                echo "Changes detected in processErrorLogs!"
                touch /workspace/processErrorLogs-changes
              else
                echo "No changes in processErrorLogs."
              fi

    - name: "gcr.io/cloud-builders/gcloud"
      id: "deploy processErrorLogs cloud function"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              if [ -f /workspace/processErrorLogs-changes ]; then
                gcloud functions deploy processErrorLogs --runtime nodejs18 --trigger-http --region europe-west3 --memory 128MB --source cloud-functions/store-error-requests
              fi

images:
    - "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"
