steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          ["build", "-t", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA", "."]

    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"]

    - name: "gcr.io/cloud-builders/docker"
      entrypoint: "bash"
      args:
          - "-c"
          - "apt-get update && apt-get install -y jq"

    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args:
          - "-c"
          - |
              SECRETS=$(gcloud secrets list --filter="labels.abc=app" --format="value(name)")

              ENV_VARS=""
              for SECRET in $SECRETS; do
                VALUE=$(gcloud secrets versions access latest --secret=$SECRET)
                ENV_VARS="$ENV_VARS,$SECRET=$VALUE"
              done

              gcloud run deploy safwan-node-express-hw \
                --image gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA \
                --region europe-west3 \
                --platform managed \
                --allow-unauthenticated \
                --set-env-vars $ENV_VARS

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "functions",
              "deploy",
              "logToBigQuery",
              "--runtime",
              "nodejs18",
              "--trigger-topic",
              "logs-topic",
              "--region",
              "europe-west3",
              "--memory",
              "128MB",
          ]
      dir: "cloud-functions/log-to-big-query"

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "functions",
              "deploy",
              "processErrorLogs",
              "--runtime",
              "nodejs18",
              "--trigger-http",
              "--region",
              "europe-west3",
              "--memory",
              "128MB",
          ]
      dir: "cloud-functions/store-error-requests"

images:
    - "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"
