steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          ["build", "-t", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA", "."]

    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"]

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "run"
          - "deploy"
          - "safwan-node-express-hw"
          - "--image"
          - "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"
          - "--region"
          - "europe-west3"
          - "--platform"
          - "managed"
          - "--allow-unauthenticated"
          - "--set-env-vars"
          - "JWT_SECRET=projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest, \
            POSTGRES_HOST=/cloudsql/$PROJECT_ID:europe-west6:hello-world-dev, \
            POSTGRES_PORT=5432, \
            POSTGRES_USER=postgres, \
            POSTGRES_PASSWORD=aabbccdd, \
            POSTGRES_DATABASE=postgres, \
            POSTGRES_SCHEMA=node-hw, \
            POSTGRES_MESSAGES_TABLE=messages, \
            POSTGRES_USERS_TABLE=users, \
            POSTRGES_TOKENS_TABLE=tokens, \
            SERVER_URL=https://$PROJECT_ID.oa.r.appspot.com"

images:
    - "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"
