steps:
    # install npm dependencies
    - name: "gcr.io/cloud-builders/npm"
      args: ["install"]

    # run formatter check
    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "format:check"]

    # run linter check
    - name: "gcr.io/cloud-builders/npm"
      args: ["run", "lint:check"]

    # deploy on app engine
    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args: [
              "-c",
              "gcloud app deploy --set-secrets=[
              NODE_ENV=projects/685414125397/secrets/NODE_ENV/versions/1,
              JWT_SECRET=projects/685414125397/secrets/JWT_SECRET/versions/1,
              POSTGRES_DATABASE=projects/685414125397/secrets/POSTGRES_DATABASE/versions/1,
              POSTGRES_HOST=projects/685414125397/secrets/POSTGRES_HOST/versions/1,
              POSTGRES_MESSAGES_TABLE=projects/685414125397/secrets/POSTGRES_MESSAGES_TABLE/versions/1,
              POSTGRES_PASSWORD=projects/685414125397/secrets/POSTGRES_PASSWORD/versions/1,
              POSTGRES_PORT=projects/685414125397/secrets/POSTGRES_PORT/versions/1,
              POSTGRES_SCHEMA=projects/685414125397/secrets/POSTGRES_SCHEMA/versions/1,
              POSTGRES_USER=projects/685414125397/secrets/POSTGRES_USER/versions/1,
              POSTGRES_USERS_TABLE=projects/685414125397/secrets/POSTGRES_USERS_TABLE/versions/1,
              POSTRGES_TOKENS_TABLE=projects/685414125397/secrets/POSTRGES_TOKENS_TABLE/versions/1,
              SERVER_URL=projects/685414125397/secrets/SERVER_URL/versions/1
              ]",
          ]
