steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          ["build", "-t", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA", "."]

    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"]

    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args:
          - "-c"
          - |
              secrets_list=$(gcloud secrets list --filter="labels.appengine=env" --format="value(name)")

              env_vars=""

              for secret_name in $secrets_list; do
                secret_value=$(gcloud secrets versions access latest --secret=$secret_name)
                env_vars="${env_vars}${secret_name}=${secret_value},"
              done

              env_vars=$(echo $env_vars | sed 's/,$//')

              gcloud run deploy safwan-node-express-hw \
                --image gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA \
                --region europe-west3 \
                --platform managed \
                --allow-unauthenticated \
                --set-env-vars $env_vars

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "functions",
              "deploy",
              "logToBigQuery",
              "--runtime",
              "nodejs18",
              "--trigger-topic",
              "logs-topic",
              "--region",
              "europe-west3",
              "--memory",
              "128MB",
          ]
      dir: "cloud-functions/log-to-big-query"

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "functions",
              "deploy",
              "processErrorLogs",
              "--runtime",
              "nodejs18",
              "--trigger-http",
              "--region",
              "europe-west3",
              "--memory",
              "128MB",
          ]
      dir: "cloud-functions/store-error-requests"

images:
    - "gcr.io/$PROJECT_ID/node-express-hw:$SHORT_SHA"
