name: "Lint and Format"

on:
    pull_request:
        branches:
            - main

jobs:
    check-linting-and-formatting:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Run the formatter
              run: npm run format

            - name: Run the linter
              run: npm run lint

            - name: Check formatting
              run: npm run format:check

            - name: Check linting
              run: npm run lint:check
